### ISSUE TITLE
Idea: Fail-fast if clientID/clientSecret missing

### ISSUE THREAD

**Issue by esnible** [observatorium/api#244]
Observatorium-API refuses to start if IssuerURL is empty:

https://github.com/observatorium/api/blob/main/authentication/oidc.go#L78

It would also be helpful if Observatorium-API failed to start without clientID or clientSecret.  I spent about 20 minutes struggling because I had left clientID blank.

With a bogus _tenant.yaml_ containing

```yaml
  oidc:
    clientID: ""
    "clientSecret": ""
    issuerURL: "https:/myhost.apps.observability-d.mycluster.p1.openshiftapps.com/auth/realms/myrealm"
```

Observatorium came up fine, but GRPC clients who sent valid headers saw:

```
ERROR:
  Code: InvalidArgument
  Message: failed to authenticate: oidc: invalid configuration, clientID must be provided or SkipClientIDCheck must be set
```

That message makes no sense to clients, only to Observatorium implementors.  I assume HTTP clients delivering logs would see something similar.
